version: "3.9"

networks:
  albums:
    driver: bridge

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - albums

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=albums
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - albums

  albums-ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    environment:
      - VIRTUAL_HOST=ui.albums.test
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=80
    networks:
      - albums

  albums-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    networks:
      - albums
    volumes:
      - /var/www/albums-api
    expose:
      - "9000"
    environment:
      - PHP_IDE_CONFIG=serverName=api.albums.test

  albums-api-nginx:
    tty: true
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:delegated
    environment:
      - VIRTUAL_HOST=api.albums.test
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=80
    networks:
      - albums
    expose:
      - "80"