# production stage for the api
FROM php:7.4-fpm as production-api
RUN apt-get update
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# install composer
FROM production-api AS temp-composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY albums-api/composer.json /app/composer.json
COPY albums-api/composer.lock /app/composer.lock

EXPOSE 9000